# Generated by Django 4.2.5 on 2024-06-27 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fakts", "0008_alter_redeemtoken_client"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10000, null=True)),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fakts.app"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="The identifier of the object. Consult the documentation for the format",
                        max_length=1000,
                    ),
                ),
                (
                    "object",
                    models.PositiveIntegerField(
                        help_text="The object id of the object, on its associated service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The Title of the Room", max_length=1000
                    ),
                ),
                ("description", models.CharField(max_length=10000, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pinned_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The users that have pinned the workspace",
                        related_name="pinned_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_streaming", models.BooleanField(default=False)),
                (
                    "text",
                    models.TextField(
                        help_text="A clear text representation of the rich comment"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time this comment got created"
                    ),
                ),
                (
                    "descendants",
                    models.JSONField(
                        default=list,
                        help_text="The immediate descendends of the comments. Think typed Rich Representation",
                    ),
                ),
                (
                    "adresses",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The users that got mentioned in this comment",
                        related_name="addressed_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The user that created this comment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_message",
                        to="kammer.agent",
                    ),
                ),
                ("attached_structures", models.ManyToManyField(to="kammer.structure")),
                (
                    "is_reply_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Is This a reply to a certain comment",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="kammer.message",
                    ),
                ),
                (
                    "targets",
                    models.ManyToManyField(
                        help_text="The agents this message targets",
                        related_name="received_messages",
                        to="kammer.agent",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="agent",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kammer.room"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="user",
            field=models.ForeignKey(
                help_text="The user that created this comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
