# Generated by Django 4.2.5 on 2025-03-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_streaming", models.BooleanField(default=False)),
                (
                    "text",
                    models.TextField(
                        help_text="A clear text representation of the rich comment"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="The time this comment got created"
                    ),
                ),
                (
                    "descendants",
                    models.JSONField(
                        default=list,
                        help_text="The immediate descendends of the comments. Think typed Rich Representation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The Title of the Room", max_length=1000
                    ),
                ),
                ("description", models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="The identifier of the object. Consult the documentation for the format",
                        max_length=1000,
                    ),
                ),
                (
                    "object",
                    models.PositiveIntegerField(
                        help_text="The object id of the object, on its associated service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The Title of the Stream", max_length=1000
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="The token of the stream", max_length=4000
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The agent that created this stream",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="kammer.agent",
                    ),
                ),
            ],
        ),
    ]
