# Generated by Django 4.2.4 on 2023-09-06 07:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("komment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="descendents",
            new_name="descendants",
        ),
    ]
