# Generated by Django 4.2.5 on 2025-03-18 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ("kammer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="pinned_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="The users that have pinned the workspace",
                related_name="pinned_rooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="adresses",
            field=models.ManyToManyField(
                blank=True,
                help_text="The users that got mentioned in this comment",
                related_name="addressed_in",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="agent",
            field=models.ForeignKey(
                help_text="The user that created this comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_message",
                to="kammer.agent",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attached_structures",
            field=models.ManyToManyField(to="kammer.structure"),
        ),
        migrations.AddField(
            model_name="message",
            name="is_reply_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Is This a reply to a certain comment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="kammer.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="targets",
            field=models.ManyToManyField(
                help_text="The agents this message targets",
                related_name="received_messages",
                to="kammer.agent",
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="app",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="kammer.room"
            ),
        ),
        migrations.AddField(
            model_name="agent",
            name="user",
            field=models.ForeignKey(
                help_text="The user that created this comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="stream",
            constraint=models.UniqueConstraint(
                fields=("agent", "title"), name="Unique stream for agent"
            ),
        ),
    ]
