# Generated by Django 4.2.5 on 2024-01-05 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("komment", "0002_rename_descendents_comment_descendants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="The time this comment got created"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="descendants",
            field=models.JSONField(
                default=list,
                help_text="The immediate descendends of the comments. Think typed Rich Representation",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="identifier",
            field=models.CharField(
                help_text="The identifier of the object. Consult the documentation for the format",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="mentions",
            field=models.ManyToManyField(
                blank=True,
                help_text="The users that got mentioned in this comment",
                related_name="mentioned_in",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="object",
            field=models.PositiveIntegerField(
                help_text="The object id of the object, on its associated service"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent of this comment. Think Thread",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="komment.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="resolved",
            field=models.DateTimeField(
                blank=True, help_text="Is this comment marked as resolved?", null=True
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user that resolved this comment",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resolved_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                help_text="A clear text representation of the rich comment"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                help_text="The user that created this comment",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
