# Generated by Django 4.2.5 on 2024-07-16 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("kammer", "0002_alter_agent_app"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The Title of the Stream", max_length=1000
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        help_text="The token of the stream", max_length=4000
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        help_text="The agent that created this stream",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="kammer.agent",
                    ),
                ),
            ],
        ),
    ]
