# Generated by Django 4.2.5 on 2024-07-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kammer", "0003_stream"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stream",
            constraint=models.UniqueConstraint(
                fields=("agent", "title"), name="Unique stream for agent"
            ),
        ),
    ]
