version: '3.7'


services:
  db:
    environment:
      POSTGRES_MULTIPLE_DATABASES: lok_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: fostgres
    image: jhnnsrs/daten:prod
    labels:
      - "arkitekt.default.service=db"
  lok_next:
    image: jhnnsrs/lok:next
    ports:
    - 8233:80
    labels:
      - "arkitekt.default.service=lok_next"
      - "traefik.enable=true"
      - "traefik.http.routers.mikro.entrypoints=mikrosecure"
      - "traefik.http.services.mikro.loadbalancer.server.port=8080"
      - "traefik.http.routers.mikro.tls.certresolver=myresolver"
  redis:
    image: redis:latest
    labels:
      - "arkitekt.default.service=redis"