# Generated by Django 4.2.4 on 2023-09-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0008_alter_accesstoken_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="token",
            field=models.CharField(max_length=6000),
        ),
    ]
