# Generated by Django 4.2.5 on 2024-05-17 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("pak", "0003_stash_shared_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="stashitem",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stashitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
