# Generated by Django 4.2.5 on 2024-05-17 15:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pak", "0004_stashitem_added_at_stashitem_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stashitem",
            name="name",
        ),
    ]
