# Generated by Django 4.2.5 on 2024-05-17 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pak", "0006_stashitem_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stashitem",
            name="position",
        ),
    ]
