# Generated by Django 5.2.1 on 2026-01-24 11:13

import authapp.models
import authlib.oauth2.rfc6749.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=48)),
                ('code', models.CharField(max_length=120, unique=True)),
                ('redirect_uri', models.TextField(default='', null=True)),
                ('response_type', models.TextField(default='')),
                ('scope', models.TextField(default='', null=True)),
                ('auth_time', models.IntegerField(default=authapp.models.now_timestamp)),
                ('nonce', models.CharField(default='', max_length=120, null=True)),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.AuthorizationCodeMixin),
        ),
        migrations.CreateModel(
            name='OAuth2Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=48, unique=True)),
                ('client_secret', models.CharField(max_length=120)),
                ('redirect_uris', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True, default='openid email profile')),
                ('token_endpoint_auth_method', models.CharField(default='client_secret_post', max_length=48)),
                ('grant_types', models.TextField(default='authorization_code refresh_token client_credentials')),
                ('response_types', models.TextField(blank=True)),
                ('id_token_signed_response_alg', models.CharField(default='RS256', max_length=48)),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.ClientMixin),
        ),
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=48)),
                ('token_type', models.CharField(max_length=40)),
                ('access_token', models.CharField(max_length=10000, unique=True)),
                ('refresh_token', models.CharField(db_index=True, max_length=10000)),
                ('scope', models.TextField(default='')),
                ('revoked', models.BooleanField(default=False)),
                ('issued_at', models.IntegerField(default=authapp.models.now_timestamp)),
                ('expires_in', models.IntegerField(default=0)),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.TokenMixin),
        ),
    ]
