# Generated by Django 5.2.1 on 2025-07-17 10:19

import authapp.models
import authlib.oauth2.rfc6749.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuth2Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=48, unique=True)),
                ('client_secret', models.CharField(max_length=120)),
                ('redirect_uris', models.TextField(blank=True)),
                ('scope', models.TextField(blank=True)),
                ('token_endpoint_auth_method', models.CharField(default='client_secret_post', max_length=48)),
                ('grant_types', models.TextField()),
                ('response_types', models.TextField(blank=True)),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.ClientMixin),
        ),
        migrations.CreateModel(
            name='OAuth2Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=48)),
                ('token_type', models.CharField(max_length=40)),
                ('access_token', models.CharField(max_length=10000, unique=True)),
                ('refresh_token', models.CharField(db_index=True, max_length=10000)),
                ('scope', models.TextField(default='')),
                ('revoked', models.BooleanField(default=False)),
                ('issued_at', models.IntegerField(default=authapp.models.now_timestamp)),
                ('expires_in', models.IntegerField(default=0)),
            ],
            bases=(models.Model, authlib.oauth2.rfc6749.models.TokenMixin),
        ),
    ]
