# Generated by Django 5.2.1 on 2026-01-24 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
        ('karakter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcode',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karakter.membership'),
        ),
        migrations.AddField(
            model_name='oauth2client',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_clients', to='karakter.membership'),
        ),
        migrations.AddField(
            model_name='oauth2token',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karakter.membership'),
        ),
    ]
