# Generated by Django 6.0.6 on 2026-07-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2client',
            name='email_template',
            field=models.CharField(blank=True, help_text="Template for the OIDC `email` claim rendered from membership variables (e.g. '{username}@corp.example'). When blank, the user's own email is used. See authapp.oidc_claims.resolve_email.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='oauth2client',
            name='membership_is_subject',
            field=models.BooleanField(default=False, help_text='Use the membership id as the OIDC `sub` claim instead of the user id. See authapp.oidc_claims.resolve_sub.'),
        ),
    ]
