# Generated by Django 5.2.1 on 2026-01-11 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_authorizationcode_organization'),
        ('karakter', '0005_role_used_by_scope_used_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizationcode',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='authorizationcode',
            name='user',
        ),
        migrations.RemoveField(
            model_name='oauth2client',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='oauth2client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='oauth2token',
            name='user',
        ),
        migrations.AddField(
            model_name='authorizationcode',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='karakter.membership'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oauth2client',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_clients', to='karakter.membership'),
        ),
        migrations.AddField(
            model_name='oauth2token',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='karakter.membership'),
            preserve_default=False,
        ),
    ]
