# Generated by Django 5.2.1 on 2026-01-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_remove_authorizationcode_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauth2token',
            old_name='membership',
            new_name='user',
        ),
    ]
