# Generated by Django 5.2.1 on 2026-01-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_rename_membership_oauth2token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2client',
            name='id_token_signed_response_alg',
            field=models.CharField(default='RS256', max_length=48),
        ),
    ]
