# Generated by Django 5.2.1 on 2026-01-15 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_oauth2client_id_token_signed_response_alg'),
        ('karakter', '0005_role_used_by_scope_used_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2client',
            name='grant_types',
            field=models.TextField(default='authorization_code refresh_token client_credentials'),
        ),
        migrations.AlterField(
            model_name='oauth2client',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_clients', to='karakter.membership'),
        ),
        migrations.AlterField(
            model_name='oauth2client',
            name='scope',
            field=models.TextField(blank=True, default='openid email profile'),
        ),
    ]
