# Generated by Django 5.2.1 on 2026-01-06 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0002_initial'),
        ('karakter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='creating_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakts.serviceinstance'),
        ),
    ]
