# Generated by Django 5.2.1 on 2025-11-13 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comchannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
