# Generated by Django 6.0.6 on 2026-07-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='brand_hue',
            field=models.FloatField(blank=True, help_text='Personal brand hue (0–360) this member picked for the organization. Tints the UI while this organization is active.', null=True),
        ),
    ]
