# Generated by Django 5.2.1 on 2026-06-14 17:34

import karakter.models
from django.db import migrations, models


def assign_unique_salts(apps, schema_editor):
    """Give each existing organization its own random device salt.

    AddField applies the callable default once for the whole column, so without
    this every pre-existing org would share a single salt.
    """
    Organization = apps.get_model('karakter', 'Organization')
    for org in Organization.objects.all():
        org.device_salt = karakter.models.generate_device_salt()
        org.save(update_fields=['device_salt'])


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='device_salt',
            field=models.CharField(default=karakter.models.generate_device_salt, editable=False, max_length=64),
        ),
        migrations.RunPython(assign_unique_salts, migrations.RunPython.noop),
    ]
