# Generated by Django 5.2.1 on 2026-01-06 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0002_initial'),
        ('karakter', '0002_role_creating_instance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('is_builtin', models.BooleanField(default=False, help_text='If this scope is a built-in scope that cannot be deleted (admin)')),
                ('creating_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakts.serviceinstance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='karakter.organization')),
            ],
            options={
                'unique_together': {('identifier', 'organization')},
            },
        ),
    ]
