# Generated by Django 6.0.6 on 2026-07-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0002_membership_brand_hue'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='brand_hue',
            field=models.FloatField(blank=True, help_text="The organization's default brand hue (0–360). Members can override it with their own membership brand hue.", null=True),
        ),
    ]
