# Generated by Django 5.2.1 on 2026-01-07 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0003_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='created_through',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='karakter.invite'),
        ),
    ]
