# Generated by Django 5.2.1 on 2025-11-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0004_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
