# Generated by Django 4.2.5 on 2024-06-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("karakter", "0004_systemmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemmessage",
            name="action",
            field=models.CharField(
                default=1, help_text="The action to take (e.g. the node)"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="systemmessage",
            name="hook",
            field=models.CharField(
                blank=True,
                help_text="A hook that the ui can use to design the message",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="systemmessage",
            name="unique",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
