# Generated by Django 5.2.1 on 2026-01-07 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0003_client_scopes'),
        ('karakter', '0004_membership_created_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='roles', to='fakts.serviceinstance'),
        ),
        migrations.AddField(
            model_name='scope',
            name='used_by',
            field=models.ManyToManyField(blank=True, related_name='scopes', to='fakts.serviceinstance'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='created_through',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_memberships', to='karakter.invite'),
        ),
    ]
