# Generated by Django 6.0.6 on 2026-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0004_rolerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='public',
            field=models.BooleanField(default=False, help_text='If true, anyone with the link can preview the invitation (organization, inviter, expiry) before signing in. Private invites require authentication before any details are shown.'),
        ),
    ]
