# Generated by Django 5.2.1 on 2025-11-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0006_remove_invite_max_uses_remove_invite_used_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='invites', to='karakter.role'),
        ),
    ]
