# Generated by Django 6.0.6 on 2026-07-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karakter', '0006_roleset'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='require_device_auth',
            field=models.BooleanField(blank=True, default=None, help_text='When set, clients created in this organization must present a device node_id (device authentication). None/False means device auth is not required.', null=True),
        ),
    ]
