"""
Django settings for kreature project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from .configuration import Settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
conf = Settings()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = conf.django.secret_key  # TODO: Change this in production

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = conf.django.debug

ALLOWED_HOSTS = conf.django.hosts

FAKTS_PROTOCOL_VERSION = "0.1.0"
DEPLOYMENT_NAME = conf.deployment.name
DEPLOYMENT_DESCRIPTION = conf.deployment.description
# Application definition

ENSURED_OPENID_APPS = [a.model_dump() for a in conf.openid_apps]


ENSURE_ORGANIZATIONS = conf.organizations
ENSURED_USERS = conf.users
ENSURED_MEMBERSHIPS = conf.memberships
REDEEM_TOKENS = conf.redeem_tokens
KOMMUNITY_PARTNERS = conf.kommunity_partners

OIDC_ISSUER = conf.oidc_issuer


if conf.ionscale is not None:
    IONSCALE_SERVER_URL = conf.ionscale.server_url
    IONSCALE_ADMIN_KEY = conf.ionscale.admin_key
    IONSCALE_COORD_URL = conf.ionscale.coord_url  # thats the public coord url
    IONSCALE_REPOSITORY = conf.ionscale.repository
    # Configured -> validate the ionscale repository at startup (fail fast).
    IONSCALE_EAGER_INIT = conf.ionscale.eager_init
else:
    IONSCALE_SERVER_URL = None
    IONSCALE_ADMIN_KEY = None
    IONSCALE_COORD_URL = None
    IONSCALE_REPOSITORY = None
    IONSCALE_EAGER_INIT = False

# IONSCALE_REPOSITORY: dotted path to a zero-arg factory returning an
# ionscale.repo.IonscaleRepo. When None, the real CLI-backed IonscaleRepository is
# used. Tests point it at ionscale.testing.FakeIonscaleRepository (see settings_test).
# IONSCALE_EAGER_INIT: when True, ionscale.apps.IonscaleConfig.ready() builds the
# repository at boot so misconfiguration fails fast.

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_probes",
    "pak",
    "authentikate",
    "authapp",
    "guardian",
    "komment",
    "channels",
    "fakts",
    "karakter",
    "ionscale",
    "health_check",
]

INSTALLED_APPS += [
    "allauth",
    "allauth.account",
    "allauth.headless",
    "allauth.socialaccount",
    # The MFA app:
    "allauth.mfa",
]

# Social provider apps (e.g. orcid, google) are configurable per deployment.
INSTALLED_APPS += conf.account.social_provider_apps


# These are the URLs to be implemented by your single-page application.
HEADLESS_FRONTEND_URLS = conf.account.headless_frontend_urls.model_dump()

ACCOUNT_EMAIL_VERIFICATION = conf.account.email_verification  # default "none": no SMTP server by default

# Authentikate section

AUTH_USER_MODEL = "karakter.User"


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
    # `allauth` specific authentication methods, such as login by email
    "allauth.account.auth_backends.AuthenticationBackend",
]

USE_X_FORWARDED_HOST = conf.django.use_x_forwarded_host

# Set when run behind a TLS-terminating reverse proxy; None otherwise.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https") if conf.django.secure_proxy_ssl_header else None


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Add the account middleware:
    "allauth.account.middleware.AccountMiddleware",
]


ACCOUNT_LOGIN_BY_CODE_ENABLED = conf.account.login_by_code_enabled  # Enable login by code
MFA_TRUST_ENABLED = conf.account.mfa_trust_enabled  # Allow trusted devices

# S3_PUBLIC_DOMAIN = f"{conf.s3.public.host}:{conf.s3.public.port}"  # TODO: FIx
AWS_ACCESS_KEY_ID = conf.datalayer.access_key
AWS_SECRET_ACCESS_KEY = conf.datalayer.secret_key
AWS_S3_ENDPOINT_URL = f"{conf.datalayer.protocol}://{conf.datalayer.host}:{conf.datalayer.port}"
# AWS_S3_PUBLIC_ENDPOINT_URL = (
#    f"{conf.minio.public.protocol}://{conf.minio.public.host}:{conf.minio.public.port}"
# )
AWS_S3_URL_PROTOCOL = f"{conf.datalayer.protocol}:"
AWS_S3_FILE_OVERWRITE = conf.datalayer.file_overwrite
AWS_QUERYSTRING_EXPIRE = conf.datalayer.querystring_expire
AWS_S3_REGION_NAME = conf.datalayer.region

MEDIA_BUCKET = conf.datalayer.media.bucket

AWS_STORAGE_BUCKET_NAME = conf.datalayer.media.bucket
AWS_DEFAULT_ACL = conf.datalayer.default_acl
# Derive TLS from the configured protocol unless explicitly overridden.
_s3_secure = conf.datalayer.secure if conf.datalayer.secure is not None else conf.datalayer.protocol == "https"
AWS_S3_USE_SSL = _s3_secure
AWS_S3_SECURE_URLS = _s3_secure

CHANNEL_LAYERS = {
    "default": {
        # This example app uses the Redis channel layer implementation channels_redis
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [(conf.redis.host, conf.redis.port)], "prefix": conf.redis.channel_prefix},
    },
}


ROOT_URLCONF = "lok_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "lok_server.wsgi.application"
ASGI_APPLICATION = "lok_server.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": conf.postgres.engine,
        "NAME": conf.postgres.db_name,
        "USER": conf.postgres.username,
        "PASSWORD": conf.postgres.password,
        "HOST": conf.postgres.host,
        "PORT": conf.postgres.port,
    }
}

if conf.email is not None:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = conf.email.host  # Use your SMTP server
    EMAIL_PORT = conf.email.port  # Common SMTP port
    EMAIL_USE_TLS = conf.email.use_tls  # Use TLS for security
    EMAIL_HOST_USER = conf.email.user  # Your email address or SMTP username
    EMAIL_HOST_PASSWORD = conf.email.password  # Your email password or SMTP password
    DEFAULT_FROM_EMAIL = conf.email.email  # Default sender email address


PRIVATE_KEY = conf.private_key
PUBLIC_KEY = conf.lok.public_key


AUTHENTIKATE = conf.authentikate.model_dump()


STRAWBERRY_DJANGO = {
    "TYPE_DESCRIPTION_FROM_MODEL_DOCSTRING": True,
    "FIELD_DESCRIPTION_FROM_HELP_TEXT": True,
    "USE_DEPRECATED_FILTERS": True,
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = conf.django.language_code

TIME_ZONE = conf.django.time_zone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CSRF_TRUSTED_ORIGINS = conf.django.csrf_trusted_origins
MY_SCRIPT_NAME = conf.django.force_script_name
STATIC_URL = MY_SCRIPT_NAME.lstrip("/") + "/" + "static/"

# WhiteNoise serves static directly from the staticfiles finders at request time
# (works under both runserver and daphne), so no collectstatic / STATIC_ROOT is needed.
WHITENOISE_USE_FINDERS = True


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "console": {
            # exact format is not important, this is the minimum information
            "format": "%(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "rich.logging.RichHandler",
            "formatter": "console",
            "rich_tracebacks": True,
        },
    },
    "loggers": {
        # root logger
        "": {
            "level": conf.django.log_level,
            "handlers": ["console"],
        },
        "oauthlib": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
        "delt": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

LOGIN_URL = "account_login"  # Redirect to login page if not authenticated
LOGOUT_URL = "account_logout"  # Redirect to logout page
LOGIN_REDIRECT_URL = "mainhome"  # Redirect to main after login
LOGOUT_REDIRECT_URL = "mainhome"  # Redirect to main after logout
ACCOUNT_LOGOUT_REDIRECT_URL = "mainhome"

# Frontend URL for redirects (used by karakter views)
KONTROL_FRONTEND_URL = conf.kontrol_frontend_url


SYSTEM_MESSAGES = conf.system_messages or [
    {
        "title": "Welcome to Lok",
        "message": "Now that you are here, you can start creating your own compositions",
    }
]

SOCIALACCOUNT_PROVIDERS = conf.socialaccount_providers
