# Generated by Django 5.2.1 on 2026-01-04 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authapp', '0002_initial'),
        ('fakts', '0001_initial'),
        ('karakter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='client',
            name='oauth2_client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='authapp.oauth2client'),
        ),
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='client',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='computenode',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compute_nodes', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='client',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='fakts.computenode'),
        ),
        migrations.AddField(
            model_name='devicecode',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fakts.client'),
        ),
        migrations.AddField(
            model_name='devicecode',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicegroup',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='computenode',
            name='device_groups',
            field=models.ManyToManyField(blank=True, related_name='compute_nodes', to='fakts.devicegroup'),
        ),
        migrations.AddField(
            model_name='instancepermission',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_permissions', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='instancepermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='layer',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='instancealias',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='fakts.layer'),
        ),
        migrations.AddField(
            model_name='devicecode',
            name='supported_layers',
            field=models.ManyToManyField(related_name='staging_device_codes', to='fakts.layer'),
        ),
        migrations.AddField(
            model_name='redeemtoken',
            name='client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_client', to='fakts.client'),
        ),
        migrations.AddField(
            model_name='redeemtoken',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tokens', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='redeemtoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='release',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='fakts.app'),
        ),
        migrations.AddField(
            model_name='release',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='client',
            name='release',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='fakts.release'),
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='servicedevicecode',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='allowed_groups',
            field=models.ManyToManyField(related_name='allowed_instances', to='auth.group'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='allowed_organizations',
            field=models.ManyToManyField(related_name='allowed_instances', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='allowed_users',
            field=models.ManyToManyField(related_name='allowed_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='denied_groups',
            field=models.ManyToManyField(related_name='denied_instances', to='auth.group'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='denied_users',
            field=models.ManyToManyField(related_name='denied_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fakts.computenode'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='karakter.mediastore'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='organization',
            field=models.ForeignKey(help_text='The organization that owns this instance. If null the instance is global.', on_delete=django.db.models.deletion.CASCADE, related_name='service_instances', to='karakter.organization'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='steward',
            field=models.ForeignKey(help_text='The user who is responsible for this instance. If null the admin is stewared by admin user.', on_delete=django.db.models.deletion.CASCADE, related_name='stewarded_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicedevicecode',
            name='instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fakts.serviceinstance'),
        ),
        migrations.AddField(
            model_name='instancepermission',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='fakts.serviceinstance'),
        ),
        migrations.AddField(
            model_name='instancealias',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='fakts.serviceinstance'),
        ),
        migrations.AddField(
            model_name='serviceinstancemapping',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='fakts.client'),
        ),
        migrations.AddField(
            model_name='serviceinstancemapping',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='fakts.serviceinstance'),
        ),
        migrations.AddField(
            model_name='servicerelease',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='fakts.service'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='fakts.servicerelease'),
        ),
        migrations.AddField(
            model_name='usedalias',
            name='alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='fakts.instancealias'),
        ),
        migrations.AddField(
            model_name='usedalias',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_aliases', to='fakts.client'),
        ),
        migrations.AddConstraint(
            model_name='computenode',
            constraint=models.UniqueConstraint(fields=('node_id', 'organization'), name='Only one node_id per organization'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('app', 'version'), name='Only one per app and version'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('release', 'user', 'organization', 'node'), name='Only one per release, user and organization'),
        ),
        migrations.AddConstraint(
            model_name='instancealias',
            constraint=models.UniqueConstraint(fields=('instance', 'host', 'port', 'ssl', 'path', 'kind'), name='Only one alias per instance and name'),
        ),
        migrations.AddConstraint(
            model_name='serviceinstancemapping',
            constraint=models.UniqueConstraint(fields=('key', 'client'), name='Only one instance per key and composition'),
        ),
        migrations.AddConstraint(
            model_name='servicerelease',
            constraint=models.UniqueConstraint(fields=('service', 'version'), name='Only one per service and version'),
        ),
        migrations.AddConstraint(
            model_name='serviceinstance',
            constraint=models.UniqueConstraint(fields=('release', 'instance_id', 'organization', 'device'), name='Only one instance_id per release, organization and device and instance'),
        ),
    ]
