# Generated by Django 4.2.5 on 2024-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fakts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True, default="No description available", null=True
            ),
        ),
    ]
