# Generated by Django 5.2.1 on 2026-01-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0002_initial'),
        ('karakter', '0003_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='clients', to='karakter.scope'),
        ),
    ]
