# Generated by Django 5.2.1 on 2025-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0002_instancealias_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancealias',
            name='ssl',
            field=models.BooleanField(default=True, help_text='If the alias is available over SSL or not. If not set, the alias is assumed to be available over SSL.'),
        ),
    ]
