# Generated by Django 5.2.1 on 2026-01-24 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=1000),
        ),
    ]
