# Generated by Django 4.2.5 on 2024-03-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fakts", "0002_alter_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="errors",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="composition",
            name="requirements_hash",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="composition",
            name="warnings",
            field=models.JSONField(default=list),
        ),
    ]
