# Generated by Django 5.2.1 on 2025-07-17 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0002_initial'),
        ('karakter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemtoken',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issued_tokens', to='karakter.organization'),
            preserve_default=False,
        ),
    ]
