# Generated by Django 6.0.6 on 2026-07-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancealias',
            name='public',
            field=models.BooleanField(default=False, help_text="If the alias is publicly reachable. If true, the coordination server can also check the alias's health directly (in addition to client-side reports), which allows checking its health from the kontrol interface."),
        ),
    ]
