# Generated by Django 5.2.1 on 2025-07-17 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_initial'),
        ('fakts', '0003_redeemtoken_organization'),
        ('karakter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='Only one per releast, tenankt and kind',
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('release', 'user', 'organization'), name='Only one per release, user and organization'),
        ),
    ]
