# Generated by Django 5.2.1 on 2025-06-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0003_instancealias_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancealias',
            name='challenge',
            field=models.TextField(default='ht', help_text='"A challenge URL to verify the alias on the client. If it returns a 200 OK, the alias is valid. It can additionally return a JSON object with a `challenge\n        key that contains the challenge to be solved by the client.'),
        ),
    ]
