# Generated by Django 5.2.1 on 2026-01-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0003_client_scopes'),
        ('karakter', '0005_role_used_by_scope_used_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinstance',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_instances', to='fakts.computenode'),
        ),
        migrations.CreateModel(
            name='LinkInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('link', models.CharField(max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_inspectors', to='karakter.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TailscaleInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('api_key', models.CharField(max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailscale_inspectors', to='karakter.organization')),
            ],
        ),
    ]
