# Generated by Django 6.0.6 on 2026-07-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0003_instancealias_public'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='instancealias',
            name='Only one alias per instance and name',
        ),
        migrations.AlterField(
            model_name='usedalias',
            name='used_at',
            field=models.DateTimeField(auto_now=True, help_text='When the client last reported this usage.'),
        ),
        migrations.AddConstraint(
            model_name='instancealias',
            constraint=models.UniqueConstraint(fields=('instance', 'host', 'port', 'ssl', 'path', 'kind'), name='Only one alias per instance host port ssl path kind'),
        ),
    ]
