# Generated by Django 4.2.5 on 2025-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fakts", "0003_client_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceinstancemapping",
            name="optional",
            field=models.BooleanField(default=False),
        ),
    ]
