# Generated by Django 4.2.5 on 2024-03-31 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("fakts", "0003_composition_errors_composition_requirements_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="composition",
            name="name",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="composition",
            name="requirements_hash",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=1000, unique=True
            ),
            preserve_default=False,
        ),
    ]
