# Generated by Django 6.0.6 on 2026-07-07 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0004_alias_constraint_and_usedalias_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('functional', models.BooleanField(default=True)),
                ('alias_reports', models.JSONField(default=dict, help_text='Raw snapshot of the reported payload: {key: {alias_id, valid, reason}}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='fakts.client')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='last_healthy_report',
            field=models.ForeignKey(blank=True, help_text='The most recent report where the client was functional; null if it has never reported healthy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fakts.report'),
        ),
    ]
