# Generated by Django 5.2.1 on 2026-01-08 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0004_alter_serviceinstance_device_linkinspector_and_more'),
        ('karakter', '0005_role_used_by_scope_used_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='karakter.organization')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='fakts.composition'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='fakts.composition'),
        ),
    ]
