# Generated by Django 5.2.1 on 2026-05-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fakts", "0004_redeemtoken_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="kommunitypartner",
            name="image_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="kommunitypartner",
            name="license_agreement",
            field=models.TextField(blank=True, help_text="Optional license agreement text shown before connecting this partner.", null=True),
        ),
        migrations.AddField(
            model_name="kommunitypartner",
            name="pre_authorize_hook",
            field=models.CharField(blank=True, help_text="Optional hook called after creating a partner composition. The response must explicitly approve the composition.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="kommunitypartner",
            name="pre_authorize_token",
            field=models.CharField(blank=True, help_text="Optional bearer token sent to the pre-authorize hook.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="kommunitypartner",
            name="short_description",
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]