# Generated by Django 4.2.5 on 2025-03-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fakts", "0004_serviceinstancemapping_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(default="No name", max_length=1000),
        ),
    ]
