# Generated by Django 5.2.1 on 2025-11-13 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0004_remove_client_only_one_per_releast_tenankt_and_kind_and_more'),
        ('karakter', '0002_alter_comchannel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='allowed_organizations',
            field=models.ManyToManyField(related_name='allowed_instances', to='karakter.organization'),
        ),
        migrations.CreateModel(
            name='ComputeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compute_nodes', to='karakter.organization')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='fakts.computenode'),
        ),
        migrations.CreateModel(
            name='InstancePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('allow', 'ALLOW'), ('deny', 'DENY')], help_text='Allow or deny access', max_length=10)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='fakts.serviceinstance')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_permissions', to='karakter.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='computenode',
            constraint=models.UniqueConstraint(fields=('node_id', 'organization'), name='Only one node_id per organization'),
        ),
        migrations.AddConstraint(
            model_name='computenode',
            constraint=models.UniqueConstraint(fields=('name', 'organization'), name='Only one uniqure node name per organization'),
        ),
    ]
