# Generated by Django 4.2.5 on 2024-04-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fakts", "0004_alter_composition_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceinstancemapping",
            name="description",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
