# Generated by Django 4.2.5 on 2025-03-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fakts", "0005_client_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="requirements_hash",
            field=models.CharField(max_length=1000),
        ),
    ]
