# Generated by Django 5.2.1 on 2026-01-08 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0005_composition_client_composition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompositionDeviceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('challenge_code', models.CharField(max_length=100, unique=True)),
                ('manifest', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField()),
                ('denied', models.BooleanField(default=False)),
                ('composition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fakts.composition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
