# Generated by Django 5.2.1 on 2025-11-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0005_serviceinstance_allowed_organizations_computenode_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='computenode',
            name='Only one uniqure node name per organization',
        ),
        migrations.AlterField(
            model_name='computenode',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
