# Generated by Django 6.0.6 on 2026-07-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0005_report_client_last_healthy_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='ionscalelayer',
            name='https_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ionscalelayer',
            name='magic_dns_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
