# Generated by Django 5.2.1 on 2026-06-05 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fakts', '0005_kommunitypartner_partner_metadata_and_hook'),
        ('karakter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinstance',
            name='composition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='fakts.composition'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='token',
            field=models.CharField(help_text='The token of the instance, used for authentication.', max_length=1000),
        ),
        migrations.AddConstraint(
            model_name='serviceinstance',
            constraint=models.UniqueConstraint(fields=('token', 'composition'), name='Only one token per composition'),
        ),
    ]
