# Generated by Django 6.0.6 on 2026-07-08 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0006_ionscalelayer_https_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeshDeviceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('challenge_code', models.CharField(max_length=100, unique=True)),
                ('requested_machine_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('machine_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('staging_ephemeral', models.BooleanField(default=False)),
                ('staging_tags', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('denied', models.BooleanField(default=False)),
                ('auth_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mesh_device_code', to='fakts.ionscaleauthkey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
