# Generated by Django 5.2.1 on 2025-11-13 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_initial'),
        ('fakts', '0006_remove_computenode_only_one_uniqure_node_name_per_organization_and_more'),
        ('karakter', '0002_alter_comchannel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='client',
            name='Only one per release, user and organization',
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('release', 'user', 'organization', 'node'), name='Only one per release, user and organization'),
        ),
    ]
