# Generated by Django 4.2.5 on 2024-04-02 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields
import fakts.enums
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("fakts", "0006_alter_release_requirements_instanceconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicecode",
            name="staging_kind",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("website", "WEBSITE (Value represent WEBSITE)"),
                    ("development", "DEVELOPMENT (Value represent DEVELOPMENT)"),
                    ("desktop", "DESKTOP (Value represent DESKTOP Aüü)"),
                ],
                choices_enum=fakts.enums.ClientKindChoices,
                default="development",
                help_text="The kind of staging client",
                max_length=11,
            ),
        ),
        migrations.CreateModel(
            name="RedeemToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(default=uuid.uuid4, max_length=1000, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(null=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redeemed_client",
                        to="fakts.client",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
