# Generated by Django 5.2.1 on 2026-01-08 12:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0006_compositiondevicecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='token',
            field=models.CharField(default=uuid.uuid4, max_length=1000, unique=True),
        ),
    ]
