# Generated by Django 5.2.1 on 2026-06-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0006_alter_serviceinstance_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='statuses',
            field=models.JSONField(default=dict, help_text="Per-requirement grant outcomes: {'key': 'granted'|'denied'|'unavailable'}."),
        ),
    ]
