# Generated by Django 5.2.1 on 2025-11-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0007_remove_client_only_one_per_release_user_and_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='public_sources',
            field=models.JSONField(default=list),
        ),
    ]
