# Generated by Django 5.2.1 on 2026-01-08 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fakts', '0008_composition_creator_composition_description'),
        ('karakter', '0005_role_used_by_scope_used_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='serviceinstance',
            name='Only one instance_id per release, organization and device and instance',
        ),
        migrations.AddConstraint(
            model_name='serviceinstance',
            constraint=models.UniqueConstraint(fields=('release', 'instance_id', 'organization', 'device', 'composition'), name='Only one instance_id per release, organization and device and instance'),
        ),
    ]
