# Generated by Django 4.2.5 on 2024-11-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fakts", "0008_alter_redeemtoken_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="redirect_uris",
            field=models.CharField(default=" ", max_length=1000),
        ),
    ]
