# Generated by Django 5.2.1 on 2025-11-30 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0008_client_public_sources'),
        ('karakter', '0007_invite_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_groups', to='karakter.organization')),
            ],
        ),
        migrations.AddField(
            model_name='computenode',
            name='device_groups',
            field=models.ManyToManyField(blank=True, related_name='compute_nodes', to='fakts.devicegroup'),
        ),
    ]
