# Generated by Django 6.0.6 on 2026-06-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0009_rename_computenode_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemtoken',
            name='allow_reredeem',
            field=models.BooleanField(default=False, help_text='If set, this token may be re-redeemed even when the manifest hash differs from the originally redeemed one.'),
        ),
        migrations.AddField(
            model_name='redeemtoken',
            name='manifest_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the manifest this token was first redeemed with. Used to detect manifest changes on re-redeem.', max_length=64, null=True),
        ),
    ]
