# Generated by Django 5.2.1 on 2026-01-10 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0009_remove_serviceinstance_only_one_instance_id_per_release_organization_and_device_and_instance_and_mor'),
        ('karakter', '0005_role_used_by_scope_used_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='karakter.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='layer',
            name='kind',
            field=models.CharField(help_text='The kind of layer', max_length=50),
        ),
    ]
