# Generated by Django 5.2.1 on 2026-01-10 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0010_layer_organization_alter_layer_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='IonscaleLayer',
            fields=[
                ('layer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fakts.layer')),
                ('tailnet_name', models.CharField(max_length=1000, unique=True)),
            ],
            bases=('fakts.layer',),
        ),
    ]
