# Generated by Django 6.0.6 on 2026-06-15 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0010_redeemtoken_allow_reredeem_redeemtoken_manifest_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemtoken',
            name='organization',
        ),
    ]
