# Generated by Django 5.2.1 on 2026-01-11 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0011_ionscalelayer'),
        ('karakter', '0005_role_used_by_scope_used_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='karakter.membership'),
        ),
    ]
