# Generated by Django 5.2.1 on 2026-01-15 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0012_client_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IonscaleAuthKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ephemeral', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_ionscale_auth_keys', to=settings.AUTH_USER_MODEL)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_keys', to='fakts.ionscalelayer')),
            ],
        ),
    ]
