# Generated by Django 5.2.1 on 2026-01-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0013_ionscaleauthkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='auth_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compositions', to='fakts.ionscaleauthkey'),
        ),
        migrations.AddField(
            model_name='ionscaleauthkey',
            name='composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ionscale_auth_keys', to='fakts.composition'),
        ),
    ]
