# Generated by Django 5.2.1 on 2026-01-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0014_composition_auth_key_ionscaleauthkey_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='private_key',
            field=models.TextField(blank=True, help_text='The private key of the instance, used for signing claims.', null=True),
        ),
    ]
