# Generated by Django 5.2.1 on 2026-01-20 13:28

import django.db.models.deletion
import fakts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_oauth2client_grant_types_and_more'),
        ('fakts', '0015_serviceinstance_private_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='KommunityPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.TextField(blank=True, default='No description available', null=True)),
                ('logo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('website_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('identifier', fakts.fields.IdentifierField(max_length=1000, unique=True)),
                ('auth_token', models.CharField(max_length=1000)),
                ('auth_url', models.CharField(max_length=1000)),
                ('oauth_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.oauth2client')),
            ],
        ),
    ]
