# Generated by Django 5.2.1 on 2026-01-20 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0016_kommunitypartner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kommunitypartner',
            name='auth_token',
        ),
    ]
