# Generated by Django 5.2.1 on 2026-01-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0017_remove_kommunitypartner_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancealias',
            name='scope',
            field=models.CharField(default='local', help_text="The scope of the alias. 'local' means that the alias is only available within the local network. 'network' means that the alias is available within the organization's network.", max_length=20),
        ),
    ]
