# Generated by Django 5.2.1 on 2026-01-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0018_instancealias_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='kommunitypartner',
            name='auto_configure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kommunitypartner',
            name='kommunity_kind',
            field=models.CharField(choices=[('open', 'OPEN'), ('restricted', 'RESTRICTED'), ('private', 'PRIVATE')], default='OPEN', help_text='The kind of kommunity', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kommunitypartner',
            name='partner_kind',
            field=models.CharField(choices=[('preauthorized', 'PREAUTHORIZED'), ('oauth2', 'OAUTH_FLOW')], default='preauthorized', help_text='The kind of partner', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kommunitypartner',
            name='preconfigured_composition',
            field=models.JSONField(blank=True, help_text='A preconfigured composition that gets created when a user redeems a token from this partner.', null=True),
        ),
        migrations.AlterField(
            model_name='kommunitypartner',
            name='auth_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
