# Generated by Django 5.2.1 on 2026-01-22 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakts', '0019_kommunitypartner_auto_configure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kommunitypartner',
            name='filter_config',
            field=models.JSONField(blank=True, default=dict, help_text="Filter conditions to determine which users/organizations this partner applies to. Example: {'email_domain_equals': ['example.com', 'test.org'], 'email_domain_ends_with': ['edu']}", null=True),
        ),
    ]
